---
ansible_ssh_common_args: -o StrictHostKeyChecking=no
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_become: true

kubelet_max_pods: 30
kubelet_kube_reserved:   cpu=100m,memory=200Mi
kubelet_system_reserved: cpu=200m,memory=100Mi
