
authorization_mode: AlwaysAllow

local_volumes:
  - name: example-quota
    size: 10M
    path: /mnt/disks/dynamic/example_quota
    type: quota
    xfs_quota_project_id: 1
    xfs_root: /mnt/disks/dynamic
    inodes: 5000
