---
ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
ansible_ssh_user: vagrant
ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
ansible_become: true

kubelet_max_pods: 30
kubelet_kube_reserved:   cpu=100m,memory=200Mi
kubelet_system_reserved: cpu=200m,memory=100Mi

