---
image: ubuntu-16-04-x64
flavor: 2gb
region_name: fra1
servers:
  - name: node1
    groups: digital-ocean,ubuntu-1604,etcds,masters
  - name: node2
    groups: digital-ocean,ubuntu-1604,etcds,masters
  - name: node3
    groups: digital-ocean,ubuntu-1604,etcds
  - name: node4
    groups: digital-ocean,ubuntu-1604
