
- name: creates directories
  file:
    path: "{{ fake_xfs_path }}"
    state: directory
    recurse: yes

- name: create files
  command: |
    dd if=/dev/zero of={{ fake_xfs_file }} bs={{ fake_xfs_size }} count=1
  args:
    creates: "{{ fake_xfs_file }}"

- name: create filesystems
  filesystem:
    fstype: "xfs"
    dev: "{{ fake_xfs_file }}"

- name: add mount to fstab
  mount:
    path: "{{ fake_xfs_path }}"
    src: "{{ fake_xfs_file }}"
    fstype: xfs
    opts: "{{ fake_xfs_opts }}"
    state: mounted

- name: remove lost+found
  file:
    path: "{{ fake_xfs_path }}/lost+found"
    state: absent
