stages:
  - prepare
  - provision
  - build
  - tests
  - e2e parallel
  - e2e serial
  - destroy

variables:
  KANIKO_IMAGE:               gcr.io/kaniko-project/executor:debug-v0.10.0
  DEV_TOOLS_IMAGE:            ${DOCKER_REGISTRY_INTERNAL}/${CI_PROJECT_PATH_SLUG}/dev-tools:${CI_COMMIT_SHA}
  DEV_TOOLS_IMAGE_EXTERNAL:   ${DOCKER_REGISTRY_EXTERNAL}/${CI_PROJECT_PATH_SLUG}/dev-tools:${CI_COMMIT_SHA}
  E2E_IMAGE:                  ${DOCKER_REGISTRY_INTERNAL}/${CI_PROJECT_PATH_SLUG}/e2e-tests:${CI_COMMIT_SHA}
  E2E_IMAGE_EXTERNAL:         ${DOCKER_REGISTRY_EXTERNAL}/${CI_PROJECT_PATH_SLUG}/e2e-tests
  KUBECONFIG:                 ${CI_PROJECT_DIR}/certificates/master/admin-kube-config
  E2E_PARALLELIZATION:        25
  OVH_REGION_NAME:            SBG3
  CI_PROVISION:               ovh
  OVH_NODES_PREFIX:           ci-${CI_PIPELINE_ID}
  OVH_KEYPAIR_NAME:           utopia-planitia-ci-runner
  DIGITAL_OCEAN_NODES_PREFIX: ci-${CI_PIPELINE_ID}
  DIGITAL_OCEAN_KEYPAIR_NAME: utopia-planitia-ci-runner

dev-tools image:
  stage: prepare
  image:
    name: ${KANIKO_IMAGE}
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY_EXTERNAL\":{\"username\":\"$DOCKER_REGISTRY_EXTERNAL_USERNAME\",\"password\":\"$DOCKER_REGISTRY_EXTERNAL_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache --reproducible --context $CI_PROJECT_DIR --dockerfile docker/dev-tools/Dockerfile --destination ${DEV_TOOLS_IMAGE_EXTERNAL}

e2e-tests image:
  stage: prepare
  image: ${KANIKO_IMAGE}
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY_EXTERNAL\":{\"username\":\"$DOCKER_REGISTRY_EXTERNAL_USERNAME\",\"password\":\"$DOCKER_REGISTRY_EXTERNAL_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache --reproducible --context $CI_PROJECT_DIR/docker/e2e-tests --dockerfile docker/e2e-tests/Dockerfile --destination ${E2E_IMAGE_EXTERNAL}

lint:
  stage: provision
  image: ${DEV_TOOLS_IMAGE}
  allow_failure: true
  script:
    - ansible-lint *.yml roles

provision:
  stage: provision
  image: ${DEV_TOOLS_IMAGE}
  retry: 2
  script:
    - mkdir -p ~/.ssh/${CI_PROVISION}
    - echo ${SSH_KEY_PRIVATE} | base64 -d > ~/.ssh/${CI_PROVISION}/id_rsa
    - echo ${SSH_KEY_PUBLIC}  | base64 -d > ~/.ssh/${CI_PROVISION}/id_rsa.pub
    - chmod 400 ~/.ssh/${CI_PROVISION}/id_rsa ~/.ssh/${CI_PROVISION}/id_rsa.pub
    - touch inventory
    - make ${CI_PROVISION}-provision
    - make certificates
    - cat inventory
  artifacts:
    paths:
      - certificates
      - inventory
      - host_vars

destroy:
  stage: destroy
  image: ${DEV_TOOLS_IMAGE}
  retry: 2
  script:
    - make ${CI_PROVISION}-destroy

destroy now:
  stage: provision
  image: ${DEV_TOOLS_IMAGE}
  script:
    - make ${CI_PROVISION}-destroy
  when: manual

deploy:
  stage: build
  image: ${DEV_TOOLS_IMAGE}
  retry: 2
  script:
    - mkdir -p ~/.ssh/${CI_PROVISION}
    - echo ${SSH_KEY_PRIVATE} | base64 -d > ~/.ssh/${CI_PROVISION}/id_rsa
    - echo ${SSH_KEY_PUBLIC}  | base64 -d > ~/.ssh/${CI_PROVISION}/id_rsa.pub
    - chmod 400 ~/.ssh/${CI_PROVISION}/id_rsa ~/.ssh/${CI_PROVISION}/id_rsa.pub
    - make deploy
  artifacts:
    paths:
      - certificates/users

redeploy:
  stage: tests
  image: ${DEV_TOOLS_IMAGE}
  retry: 2
  script:
    - mkdir -p ~/.ssh/${CI_PROVISION}
    - echo ${SSH_KEY_PRIVATE} | base64 -d > ~/.ssh/${CI_PROVISION}/id_rsa
    - echo ${SSH_KEY_PUBLIC}  | base64 -d > ~/.ssh/${CI_PROVISION}/id_rsa.pub
    - chmod 400 ~/.ssh/${CI_PROVISION}/id_rsa ~/.ssh/${CI_PROVISION}/id_rsa.pub
    - make deploy | tee deploy.log
    - grep "changed=0    unreachable=0    failed=0" deploy.log | wc -l | grep 4

bats:
  stage: tests
  image: ${DEV_TOOLS_IMAGE}
  retry: 2
  script:
    - mkdir -p ~/.ssh/${CI_PROVISION}
    - echo ${SSH_KEY_PRIVATE} | base64 -d > ~/.ssh/${CI_PROVISION}/id_rsa
    - echo ${SSH_KEY_PUBLIC}  | base64 -d > ~/.ssh/${CI_PROVISION}/id_rsa.pub
    - chmod 400 ~/.ssh/${CI_PROVISION}/id_rsa ~/.ssh/${CI_PROVISION}/id_rsa.pub
    - make bats

cleanup e2e ns:
  stage: e2e parallel
  image: ${DEV_TOOLS_IMAGE}
  script:
    - make delete-e2e-namespaces
  when: manual

conformance:
  stage: e2e parallel
  image: ${E2E_IMAGE}
  retry: 2
  script:
    - make delete-e2e-namespaces
    - make conformance
    - make port-forward

serial conformance:
  stage: e2e serial
  image: ${E2E_IMAGE}
  retry: 2
  script:
    - make delete-e2e-namespaces
    - make serial
