---
- hosts: masters
  tasks:
    - name: create etcd certificates
      import_role:
        name: etcd-certificates
      delegate_to: localhost
      run_once: true
    - name: create kubernetes certificates
      import_role:
        name: master-certificates
      delegate_to: localhost
      run_once: true
- hosts: all
  tasks:
    - name: create wireguard keys
      import_role:
        name: wireguard-certificates
      delegate_to: localhost

