---
- hosts: masters
  tasks:
    - name: create etcd certificates
      import_role:
        name: etcd-certificates
      delegate_to: localhost
      run_once: true
    - name: create kubernetes certificates
      import_role:
        name: master-certificates
      delegate_to: localhost
      run_once: true
    - name: create weave certificates
      import_role:
        name: weave-certificates
      delegate_to: localhost
      run_once: true
