---
- hosts: all
  tasks:
    - name: wait for ssh to be available
      local_action: wait_for port=22 host="{{ ansible_host }}" search_regex=OpenSSH

- hosts: localhost
  roles:
    - { role: etcd-certificates }
    - { role: master-certificates }

- hosts: ubuntu-1604
  roles:
    - { role: ubuntu-1604 }

- hosts: all
  roles:
    - { role: docker }
    - { role: node }

- hosts: etcds
  pre_tasks:
    - name: set etcd_id
      set_fact: etcd_id={{ item.0 + 1 }}
      with_indexed_items: "{{ groups['etcds'] }}"
      when: item.1 == inventory_hostname
  roles:
    - { role: etcd }

- hosts: masters
  roles:
    - { role: master }

- hosts: all:!masters
  roles:
    - { role: master-proxy }
