---
- hosts: all
  tasks:
    - name: wait for ssh to be available
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        search_regex: OpenSSH
      delegate_to: localhost

- hosts: all
  roles:
    - role: node
      become: yes
      become_user: root
    - role: registry-mirror
      become: yes
      become_user: root

- hosts: etcds
  pre_tasks:
    - name: set etcd_id
      set_fact: etcd_id={{ item.0 + 1 }}
      with_indexed_items: "{{ groups['etcds'] }}"
      when: item.1 == inventory_hostname
  roles:
    - role: etcd
      become: yes
      become_user: root

- hosts: masters
  tasks:
    - name: create user access tokens
      import_role:
        name: authentication-tokens
      delegate_to: localhost
      run_once: true
  roles:
    - role: master
      become: yes
      become_user: root

- hosts: all:!masters
  roles:
    - role: master-proxy
      become: yes
      become_user: root
