---
- hosts: all
  tasks:
    - name: wait for ssh to be available
      local_action: wait_for port=22 host="{{ ansible_host }}" search_regex=OpenSSH

- hosts: all
  roles:
    - { role: local-volumes }