---
- name: remove public ssh key
  os_keypair:
    state: absent
    name: "{{ OVH_KEYPAIR_NAME }}"
  when: OVH_KEYPAIR_NAME is defined

- name: remove instances
  os_server:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ OVH_NODES_PREFIX }}-node1"
    - "{{ OVH_NODES_PREFIX }}-node2"
    - "{{ OVH_NODES_PREFIX }}-node3"
    - "{{ OVH_NODES_PREFIX }}-node4"
