---
- name: remove public ssh key
  os_keypair:
    state: absent
    name: "{{ OVH_KEYPAIR_NAME }}"
  when: OVH_KEYPAIR_NAME is defined

- name: remove instances
  os_server:
    name: "{{ OVH_NODES_PREFIX }}-{{ item }}"
    state: absent
  with_items:
    - "node1"
    - "node2"
    - "node3"
    - "node4"
  when: item == PROVISION_NODE | default(item)
