---

- name: create kubernetes ssl directory
  file:
    path: /etc/master-forwarder
    state: directory
    recurse: true

- name: create master-forwarder config
  template: src=nginx.conf.j2 dest=/etc/master-forwarder/nginx.conf

- name: checksum of master certificates
  shell: md5sum /etc/master-forwarder/nginx.conf | head -c 32
  register: master_forwarder_config_hashsum
  changed_when: false

- name: "set master_forwarder_config_hashsum variable"
  set_fact:
    master_forwarder_config_hashsum: "{{ master_forwarder_config_hashsum.stdout }}"

- name: install master-forwarder
  template:
    src: master-forwarder.yml.j2
    dest: /etc/kubernetes/manifests/master-forwarder.yml
