---

- name: disable systemd resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: configure upstream dns
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
