---
- name: install apt-transport-https
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https

- name: add projectatomic PPA repo
  apt_repository:
    repo: "ppa:projectatomic/ppa"
    state: present
    filename: projectatomic
  notify: update repositories

- meta: flush_handlers

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - cri-o-1.13
    - podman
    - iproute2
  notify: restart crio

- name: configure crio
  template:
    src: registries.conf
    dest: /etc/containers/registries.conf
  notify: restart crio

- name: install crictl
  command: podman run --rm -v /usr/local/bin:/go/bin golang:1.11.5 go get -v -u github.com/kubernetes-incubator/cri-tools/cmd/crictl
  args:
    creates: /usr/local/bin/crictl
