---

- name: load kernel modules into runtime
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: load kernel modules at bootup
  lineinfile:
    path: /etc/modules
    regexp: "{{ item }}"
    line: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: configure kernel modules
  lineinfile:
    path: /etc/sysctl.conf
    line: '{{ item }}'
  with_items:
    - net.bridge.bridge-nf-call-iptables  = 1
    - net.bridge.bridge-nf-call-ip6tables = 1
  notify: apply kernel configuration

- name: install crio
  import_tasks: install.yml

- meta: flush_handlers

- name: start crio
  systemd:
    name: crio
    state: started
    enabled: yes
