---
cni_version: v0.6.0

cni_packages:
  - url: https://github.com/containernetworking/cni/releases/download/{{ cni_version }}/cni-amd64-{{ cni_version }}.tgz
    checksum: sha256:a7f84a742c8f3a95843b3cc636444742554a4853835649ec371a07c841daebab
    local_file: /opt/cni.tar.gz
    creates: /opt/cni/bin/cnitool
  - url: https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-amd64-{{ cni_version }}.tgz
    checksum: sha256:f04339a21b8edf76d415e7f17b620e63b8f37a76b2f706671587ab6464411f2d
    local_file: /opt/cni-plugins.tar.gz
    creates: /opt/cni/bin/portmap

kubelet_max_pods: 250
kubelet_max_open_files:             250000
kubelet_kube_reserved:              cpu=500m,memory=1Gi
kubelet_system_reserved:            cpu=500m,memory=1Gi
kubelet_eviction_hard:              memory.available<2Gi,nodefs.available<5%,nodefs.inodesFree<5%,imagefs.available<5%,imagefs.inodesFree<5%
kubelet_eviction_soft:              memory.available<4Gi,nodefs.available<10%,nodefs.inodesFree<10%,imagefs.available<10%,imagefs.inodesFree<10%
kubelet_eviction_soft_grace_period: memory.available=2m30s,nodefs.available=2m30s,nodefs.inodesFree=2m30s,imagefs.available=2m30s,imagefs.inodesFree=2m30s
