---

- name: create master proxy directory
  file:
    path: /etc/master-proxy
    state: directory
    recurse: true

- name: create master-proxy config
  template: src=nginx.conf.j2 dest=/etc/master-proxy/nginx.conf

- name: checksum of master certificates
  shell: md5sum /etc/master-proxy/nginx.conf | head -c 32
  register: master_proxy_config_hashsum
  changed_when: false

- name: "set master_proxy_config_hashsum variable"
  set_fact:
    master_proxy_config_hashsum: "{{ master_proxy_config_hashsum.stdout }}"

- name: install master-proxy
  template:
    src: master-proxy.yml.j2
    dest: /etc/kubernetes/manifests/master-proxy.yml

- name: wait for master-proxy to be available
  wait_for:
    port: 6443
