---
- name: generate SSH key
  command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa

- name: launch instances
  os_server:
    name: "{{ OVH_NODES_PREFIX }}-{{ item.name }}"
    state: present
    key: /root/.ssh/id_rsa.pub
    image: "{{ image }}"
    flavor: "{{ flavor }}"
  with_items: "{{ servers }}"
  register: "os_hosts"
  when: item.name == OVH_NODE | default(item.name)

- name: add hosts to inventory
  add_host:
    name: "{{ item.item.name }}"
    groups: "{{ item.item.groups }}"
    ansible_host: "{{ item.openstack.accessIPv4 }}"
  with_items: "{{ os_hosts.results }}"
  when: item.openstack is defined
