---
apiserver_max_requests_inflight:          "{{ nodes_count|int * kubelet_max_pods * 1.4 }}"
apiserver_max_mutating_requests_inflight: "{{ nodes_count|int * kubelet_max_pods * 0.9 }}"
apiserver_limit_target_ram_mb:            "{{ 350 + (nodes_count|int * kubelet_max_pods * 5) }}"

scheduler_api_qps:   "{{ apiserver_max_requests_inflight|int * 0.4 }}"
scheduler_api_burst: "{{ apiserver_max_requests_inflight|int * 0.6 }}"

apiserver_requests_cpu:             100m
apiserver_requests_memory:          "{{ 20 + (apiserver_limit_target_ram_mb|int * 1.1) | int }}Mi"
apiserver_limits_cpu:               1000m
apiserver_limits_memory:            "{{ apiserver_requests_memory }}"
controller_manager_requests_cpu:    50m
controller_manager_requests_memory: "{{ 20 + (nodes_count|int * kubelet_max_pods) }}Mi"
controller_manager_limits_cpu:      1000m
controller_manager_limits_memory:   "{{ controller_manager_requests_memory }}"
scheduler_requests_cpu:             50m
scheduler_requests_memory:          "{{ 100 + (nodes_count|int * kubelet_max_pods) }}Mi"
scheduler_limits_cpu:               1000m
scheduler_limits_memory:            "{{ scheduler_requests_memory }}"

authorization_mode: Node,RBAC

service_node_port_range: "30000-32767"
