---

- name: restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: apply kernel configuration
  command: sysctl -p

- name: update repositories
  apt:
    update_cache: yes
