---

- name: reload systemd
  command: systemctl daemon-reload

- name: restart kubelet
  service:
    name: kubelet
    enabled: yes
    state: restarted
    enabled: yes

- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: yes

