---

- name: restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
