---
- name: remove public ssh key
  digital_ocean:
    state: absent
    command: ssh
    name: "{{ DIGITAL_OCEAN_KEYPAIR_NAME }}"
  when: DIGITAL_OCEAN_KEYPAIR_NAME is defined

- name: remove instances
  digital_ocean:
    command: droplet
    name: "{{ DIGITAL_OCEAN_NODES_PREFIX }}-{{ item }}"
    state: absent
    unique_name: yes
  with_items:
    - "node1"
    - "node2"
    - "node3"
    - "node4"
  when: item == PROVISION_NODE | default(item)
