---

- name: create directory to keep file storage
  file:
    path: "{{ item.file | dirname }}"
    state: directory
    recurse: yes

- name: create file storage
  command: |
    dd if=/dev/zero of={{ item.file }} bs={{ item.size }} count=1
  args:
    creates: "{{ item.file }}"
  register: created_files

- name: create filesystem in block
  filesystem:
    fstype: "xfs"
    dev: "{{ item.file }}"

- name: create mountpoint
  file:
    path: "{{ item.path }}"
    state: directory
    recurse: yes

- name: add mount to fstab
  mount:
    path: "{{ item.path }}"
    src: "{{ item.file }}"
    fstype: "xfs"
    opts: "{{ item.opts | default('defaults') }}"
    state: mounted

- name: remove lost+found
  file:
    path: "{{ item.path }}/lost+found"
    state: absent
