---

- name: set up a Certificate directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  items:
    - "{{ master_cert_dir }}"
    - "{{ users_cert_dir }}"

- name: render master certificate configuration
  template:
    src: "master.json.j2"
    dest: "{{ master_cert_dir }}/master.json"

- name: render nodes certificate configuration
  template:
    src: "node.json.j2"
    dest: "{{ master_cert_dir }}/node-{{ item }}.json"
  with_items: "{{ groups['all'] }}"

- name: set up a Certificate Authority
  shell: cfssl gencert -initca {{ master_config_dir }}/ca.json | cfssljson -bare ca
  args:
    chdir: "{{ master_cert_dir }}"
    creates: "ca-key.pem"

- name: set up admin certificate
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config={{ master_config_dir }}/config.json -profile=kubernetes {{ master_config_dir }}/admin.json | cfssljson -bare admin
  args:
    chdir: "{{ master_cert_dir }}"
    creates: "admin-key.pem"

- name: set up admin config file
  shell: |
    kubectl --kubeconfig=admin-kube-config config set-cluster default --server=https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:6443 --embed-certs=true --certificate-authority=ca.pem &&
    kubectl --kubeconfig=admin-kube-config config set-credentials default --embed-certs=true --client-certificate=admin.pem --client-key=admin-key.pem &&
    kubectl --kubeconfig=admin-kube-config config set-context default --cluster=default --user=default --namespace=default &&
    kubectl --kubeconfig=admin-kube-config config use-context default
  args:
    chdir: "{{ master_cert_dir }}"
    creates: admin-kube-config

- name: set up kube-proxy certificate
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config={{ master_config_dir }}/config.json -profile=kubernetes {{ master_config_dir }}/kube-proxy.json | cfssljson -bare kube-proxy
  args:
    chdir: "{{ master_cert_dir }}"
    creates: "kube-proxy-key.pem"

- name: set up kube-proxy file
  shell: |
    kubectl --kubeconfig=kube-proxy-config config set-cluster default --server=https://127.0.0.1:6443 --embed-certs=true --certificate-authority=ca.pem &&
    kubectl --kubeconfig=kube-proxy-config config set-credentials default --embed-certs=true --client-certificate=admin.pem --client-key=admin-key.pem &&
    kubectl --kubeconfig=kube-proxy-config config set-context default --cluster=default --user=default &&
    kubectl --kubeconfig=kube-proxy-config config use-context default
  args:
    chdir: "{{ master_cert_dir }}"
    creates: kube-proxy-config

- name: set up nodes certificate
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config={{ master_config_dir }}/config.json -profile=kubernetes node-{{ item }}.json | cfssljson -bare node-{{ item }}
  args:
    chdir: "{{ master_cert_dir }}"
    creates: "node-{{ item }}-key.pem"
  with_items: "{{ groups['all'] }}"

- name: set up nodes config file
  shell: |
    kubectl --kubeconfig=node-{{ item }}-kube-config config set-cluster default --server=https://127.0.0.1:6443 --embed-certs=true --certificate-authority=ca.pem &&
    kubectl --kubeconfig=node-{{ item }}-kube-config config set-credentials default --embed-certs=true --client-certificate=node-{{ item }}.pem --client-key=node-{{ item }}-key.pem &&
    kubectl --kubeconfig=node-{{ item }}-kube-config config set-context default --cluster=default --user=default &&
    kubectl --kubeconfig=node-{{ item }}-kube-config config use-context default
  args:
    chdir: "{{ master_cert_dir }}"
    creates: "node-{{ item }}-kube-config"
  with_items: "{{ groups['all'] }}"

- name: set up master certificate
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config={{ master_config_dir }}/config.json -profile=kubernetes master.json | cfssljson -bare master
  args:
    chdir: "{{ master_cert_dir }}"
    creates: "master-key.pem"

- name: set up user config files
  shell: |
    kubectl --kubeconfig={{ item.username }}-kube-config config set-cluster {{ cluster.name }} --server=https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:6443 --embed-certs=true --certificate-authority={{ master_cert_dir }}/ca.pem &&
    kubectl --kubeconfig={{ item.username }}-kube-config config set-credentials {{ item.username }} --token={{ item.token }} &&
    kubectl --kubeconfig={{ item.username }}-kube-config config set-context {{ cluster.name }} --cluster={{ cluster.name }} --user={{ item.username }} --namespace=default &&
    kubectl --kubeconfig={{ item.username }}-kube-config config use-context {{ cluster.name }}
  args:
    chdir: "{{ users_cert_dir }}"
    creates: "{{ item.username }}-kube-config"
  with_items: "{{ cluster.users }}"
