---

- name: add projectatomic PPA repo
  apt_repository:
    repo: "ppa:projectatomic/ppa"
    state: present
    filename: projectatomic
  notify: update repositories

- meta: flush_handlers

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - containernetworking-plugins
