
---

- name: kubelet kernel default values
  lineinfile:
    path: /etc/sysctl.conf
    line: '{{ item }}'
  with_items:
    - "vm.overcommit_memory = 1"
    - "kernel.panic = 10"
    - "kernel.panic_on_oops = 1"
  notify: apply kernel configuration

- meta: flush_handlers

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /etc/kubernetes/manifests/
    - /etc/kubelet/
    - /usr/local/bin/

- name: copy kubelet certificates
  copy:
    src: "{{ master_cert_dir }}/{{ item.local }}"
    dest: "/etc/kubelet/{{ item.remote }}"
  with_items:
    - { local: 'ca.pem', remote: 'ca.pem' }
    - { local: 'node-{{ inventory_hostname }}.pem', remote: 'kubelet.pem' }
    - { local: 'node-{{ inventory_hostname }}-key.pem', remote: 'kubelet-key.pem' }
    - { local: 'node-{{ inventory_hostname }}-kube-config', remote: 'kubeconfig' }
  no_log: true
  notify:
    - restart kubelet

- name: download kubelet binary
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64/kubelet"
    dest: "/usr/local/bin/kubelet-{{ kubernetes_version }}"
    mode: 0771

- name: select kubelet version
  file:
    state: link
    force: yes
    path: /usr/local/bin/kubelet
    src: "/usr/local/bin/kubelet-{{ kubernetes_version }}"
  notify:
    - restart kubelet

- name: create kubelet service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
    - restart kubelet

- meta: flush_handlers

- name: start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started

- name: wait for kubelet to be available
  wait_for:
    port: 10248

- name: configure logrotate
  template:
    src: kubelet-logrotate.j2
    dest: /etc/logrotate.d/kubelet

- name: install socat
  package:
    name: "socat"
    state: present
