---

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /etc/kubernetes/manifests/
    - /etc/kube-proxy/

- name: copy kube-proxy certificates
  copy:
    src: "{{ master_cert_dir }}/kube-proxy-config"
    dest: "/etc/kube-proxy/kubeconfig"
  no_log: true

- name: copy kube-proxy config
  template:
    src: kube-proxy-config.j2
    dest: /etc/kube-proxy/config

- name: checksum of kube proxy certificates
  shell: |
    set -euo pipefail
    md5sum /etc/kube-proxy/kubeconfig | head -c 32
  args:
    executable: /bin/bash
  register: kube_proxy_certificates_hashsum
  changed_when: false

- name: checksum of kube proxy config
  shell: |
    set -euo pipefail
    md5sum /etc/kube-proxy/config | head -c 32
  args:
    executable: /bin/bash
  register: kube_proxy_config_hashsum
  changed_when: false

- name: "set kube_proxy_config_hashsum variable"
  set_fact:
    kube_proxy_config_hashsum: "{{ kube_proxy_certificates_hashsum.stdout }}-{{ kube_proxy_config_hashsum.stdout }}"

- name: install kube-proxy
  template:
    src: kube-proxy.yml.j2
    dest: /etc/kubernetes/manifests/kube-proxy.yml
