---

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /etc/kubernetes/manifests/

- name: create kubelet service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
    - reload systemd
    - restart kubelet

- meta: flush_handlers

- name: start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
