---

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /etc/cni/net.d/
    - /usr/local/bin/

- name: weave binary
  copy:
    src: weave
    dest: /usr/local/bin/weave
    mode: 0755
