
---
- name: base64 encoded resources webhook client certificate
  # todo: figure useing instead of server.pem ca.pem or client pem or better why client.pem is not working
  local_action: shell cd {{ resources_webhook_cert_dir }}; cat ca.pem | base64 -w 0
  register: resources_webhook_client_cert_base64_cli
  changed_when: false

- name: "set resources_webhook_client_cert_base64 variable"
  set_fact:
    resources_webhook_client_cert_base64: "{{ resources_webhook_client_cert_base64_cli.stdout }}"

- name: install resources_webhook
  template:
    src: ResourcesWebhookConfiguration.yml.j2
    # dest: /etc/kubernetes/manifests/ResourcesWebhookConfiguration.yml
    dest: "{{ addons_dir }}/ResourcesWebhookConfiguration.yaml"
  delegate_to: localhost
  run_once: true
