---

- name: update repositories
  apt:
    update_cache: yes

- name: restart crio
  systemd:
    name: crio
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: apply kernel configuration
  command: sysctl -p
