---

- name: create kubernetes ssl directory
  file:
    path: /etc/kubernetes/ssl/
    state: directory
    recurse: true

- name: copy etcd certificates
  copy:
    src: "{{ etcd_cert_dir }}/{{ item.local }}"
    dest: "/etc/kubernetes/ssl/{{ item.remote }}"
  with_items:
    - { local: 'ca.pem', remote: 'etcd-ca.pem' }
    - { local: 'client.pem', remote: 'etcd.pem' }
    - { local: 'client-key.pem', remote: 'etcd-key.pem' }
  no_log: true

- name: copy kubernetes certificates
  copy:
    src: "{{ master_cert_dir }}/{{ item.local }}"
    dest: "/etc/kubernetes/ssl/{{ item.remote }}"
  with_items:
    - { local: 'ca.pem', remote: 'kubernetes-ca.pem' }
    - { local: 'master.pem', remote: 'master.pem' }
    - { local: 'master-key.pem', remote: 'master-key.pem' }
  no_log: true

- name: checksum of etcd certificates
  local_action: shell cd {{ etcd_cert_dir }}; md5sum ca.pem server.pem server-key.pem member.pem member-key.pem | md5sum | head -c 32
  register: etcd_cert_hashsum
  changed_when: false

- name: checksum of master certificates
  local_action: shell cd {{ master_cert_dir }}; md5sum ca.pem server.pem server-key.pem member.pem member-key.pem | md5sum | head -c 32
  register: master_cert_hashsum
  changed_when: false

- name: "set master_cert_hashsum variable"
  set_fact:
    master_cert_hashsum: "{{ master_cert_hashsum.stdout }}-{{ etcd_cert_hashsum.stdout }}"

- name: install master
  template:
    src: master.yml.j2
    dest: /etc/kubernetes/manifests/master.yml
