---

- name: create kubernetes ssl directory
  file:
    path: /etc/kubernetes/ssl/
    state: directory
    recurse: true

- name: copy etcd certificates
  copy:
    src: "{{ etcd_cert_dir }}/{{ item.local }}"
    dest: "/etc/kubernetes/ssl/{{ item.remote }}"
  with_items:
    - { local: 'ca.pem', remote: 'etcd-ca.pem' }
    - { local: 'client.pem', remote: 'etcd.pem' }
    - { local: 'client-key.pem', remote: 'etcd-key.pem' }
  no_log: true

- name: copy kubernetes certificates
  copy:
    src: "{{ master_cert_dir }}/{{ item.local }}"
    dest: "/etc/kubernetes/ssl/{{ item.remote }}"
  with_items:
    - { local: 'ca.pem', remote: 'kubernetes-ca.pem' }
    - { local: 'client-ca.pem', remote: 'kubernetes-client-ca.pem' }
    - { local: 'master.pem', remote: 'master.pem' }
    - { local: 'master-key.pem', remote: 'master-key.pem' }
  no_log: true

- name: install token-auth-file
  template:
    src: token-auth-file.j2
    dest: /etc/kubernetes/token-auth-file

- name: configure audit logging
  copy:
    src: audit-policy.yaml
    dest: /etc/kubernetes/audit-policy.yaml

- name: checksum of etcd certificates
  local_action: shell cd {{ etcd_cert_dir }}; md5sum etcd-ca.pem etcd.pem etcd-key.pem | md5sum | head -c 32
  register: etcd_cert_hashsum
  changed_when: false

- name: checksum of master certificates
  local_action: shell cd {{ master_cert_dir }}; md5sum kubernetes-ca.pem kubernetes-client-ca.pem master.pem master-key.pem | md5sum | head -c 32
  register: master_cert_hashsum
  changed_when: false

- name: checksum of token-auth-file
  action: shell md5sum /etc/kubernetes/token-auth-file | head -c 32
  register: token_auth_file_hashsum
  changed_when: false

- name: checksum of audit-policy
  action: shell md5sum /etc/kubernetes/audit-policy.yaml | head -c 32
  register: audit_policy_file_hashsum
  changed_when: false

- name: "set master_config_hash variable"
  set_fact:
    master_config_hash: "{{ master_cert_hashsum.stdout }}-{{ etcd_cert_hashsum.stdout }}-{{ token_auth_file_hashsum.stdout }}-{{ audit_policy_file_hashsum.stdout }}"

- name: install master
  template:
    src: master.yml.j2
    dest: /etc/kubernetes/manifests/master.yml

- name: wait for insecure apiserver to be available
  wait_for:
    port: 8080

- name: wait for secure apiserver to be available
  wait_for:
    port: 6443

- name: wait for scheduler to be available
  wait_for:
    port: 10251

- name: wait for controller-manager to be available
  wait_for:
    port: 10252
