---

- name: load kernel modules into runtime
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - bridge
    - br_netfilter

- name: load kernel modules at bootup
  lineinfile:
    path: /etc/modules
    regexp: "{{ item }}"
    line: "{{ item }}"
  with_items:
    - overlay
    - bridge
    - br_netfilter

- name: install docker
  import_tasks: install.yml

- name: configure docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
