---

- name: Set up a Certificate directory
  file:
    path: "{{ etcd_cert_dir }}"
    state: directory
    recurse: true

- name: set up a etcd certificate authority
  shell: |
    set -euo pipefail
    cfssl gencert -initca {{ etcd_config_dir }}/ca.json | cfssljson -bare ca
  args:
    chdir: "{{ etcd_cert_dir }}"
    creates: "ca-key.pem"
    executable: /bin/bash

- name: create etcd certificate
  shell: |
    set -euo pipefail
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config={{ etcd_config_dir }}/config.json \
    -profile={{ item }} {{ etcd_config_dir }}/{{ item }}.json | cfssljson -bare {{ item }}
  args:
    chdir: "{{ etcd_cert_dir }}"
    creates: "{{ item }}-key.pem"
    executable: /bin/bash
  with_items:
    - kube-apiserver-etcd-client
    - kube-etcd-healthcheck-client
    - kube-etcd-peer
    - kube-etcd
