---
- debug:
    msg: "TOKEN {{ HCLOUD_TOKEN }} "
# create an ssh key
# - hcloud_ssh_key:
#     name: hcloud-ssh-key
#     public_key: "{{lookup('file', './hcloud-ssh-key/id_rsa.pub')}}"

- hcloud_ssh_key:
    state: list
<<<<<<< HEAD
  register: hcloud_ssh_keys

- debug:
    msg: "ssh_keys {{ hcloud_ssh_keys }} "
- debug:
    msg: "sshkey.sshkey {{ hcloud_ssh_keys.ssh_keys }} "

=======
    token : "{{ HCLOUD_TOKEN }}"
  register: 'hcloud_ssh_keys'
>>>>>>> 4d3129e9a5cbf9944df118fa841633f888379448
# create some servers at once
- hcloud_server:
     name:
     - "{{ HCLOUD_NODES_PREFIX }}-{{ item.name }}"
     image: "{{ image }}"
     server_type: "{{ server_type }}"
     location: "{{ location }}"
     ssh_keys: "{{ hcloud_ssh_keys.ssh_keys }}"
     token : "{{ HCLOUD_TOKEN }}"
  with_items: "{{ servers }}"
  register: hcloud_details

#- debug:
#    msg: "System {{ item.servers[0].status }} "
#  with_items: "{{ hcloud_details.results }}"


# ensure server is running (if the server already exists)
# - hcloud_server:
#    name:
#    - "{{ HCLOUD_NODES_PREFIX }}-{{ item.name }}"
#    state: running
#   with_items: "{{ servers }}"

- name: remove old inventory file
  copy:
    dest: ./inventory
    content: ""

- name: load empty inventory
  meta: refresh_inventory

- name: add hosts to inventory
  add_host:
    name: "{{ HCLOUD_NODES_PREFIX }}-{{ item.item.name }}"
    groups: "{{ item.item.groups }}"
    ansible_host: "{{ item.servers[0].public_ipv4 }}"
  with_items: "{{ hcloud_details.results }}"
