---
- name: generate SSH key directory
  file:
    path: /root/.ssh/hcloud/
    state: directory
    recurse: yes

- name: generate SSH key
  command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/hcloud/id_rsa -q -N ""
  args:
    creates: /root/.ssh/hcloud/id_rsa

- name: upload public ssh key
  digital_ocean:
    state: present
    command: ssh
    name: "{{ HCLOUD_KEYPAIR_NAME }}"
    ssh_pub_key: "{{ lookup('file', '/root/.ssh/hcloud/id_rsa.pub') }}"
  register: ssh_key_at_hcloud

# create three servers at once
- hcloud_server:
    name:
    - node1
    - node2
    - node3
    - node4
    image: ubuntu-16.04
    server_type: cx51
    location: nbg1
    ssh_keys: "{{ HCLOUD_KEYPAIR_NAME }}"
    token : HCLOUD_TOKEN
    

# ensure server is running (if the server already exists)
- hcloud_server:
    name:
      - node1
      - node2
      - node3
      - node4
    state: running
