---
# - name: generate SSH key directory
#   file:
#     path: /root/.ssh/hcloud/
#     state: directory
#     recurse: yes
#
# - name: generate SSH key
#   command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/hcloud/id_rsa -q -N ""
#   args:
#     creates: /root/.ssh/hcloud/id_rsa

# create three servers at once
- hcloud_server:
    name:
    - node1
    - node2
    - node3
    - node4
    image: ubuntu-16.04
    server_type: cx51
    location: nbg1
#    ssh_keys: "{{ HCLOUD_KEYPAIR_NAME }}"
    token : MiKjIhmsivQKZBPas5f3ld1phv2SGUAUu8I5fm4x0JINNLUPFd4bZpk7TibxZYle


# ensure server is running (if the server already exists)
- hcloud_server:
    name:
      - node1
      - node2
      - node3
      - node4
    state: running
