---

- name: install python
  raw: ( test -e /usr/bin/python && echo "/usr/bin/python found" ) || ( apt -y update && apt install -y python )
  register: install_python_result
  changed_when: "'/usr/bin/python found' not in install_python_result.stdout"

- name: install apt-transport-https
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https

- name: add docker deb repo key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker deb repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    filename: docker
  notify: update repositories

- meta: flush_handlers

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce=17.03.2~ce-0~ubuntu-xenial
    - socat
