---
- name: add ppa
  apt_repository:
    repo: 'ppa:wireguard/wireguard'
    state: present
    filename: wireguard

- name: install package
  apt:
    name: wireguard=0.0.20190123-wg1~bionic
    state: present
  notify: restart wg-quick@wg0

- name: set private ip
  set_fact:
    wireguard_private_ip: "10.0.1.{{ groups['all'].index(inventory_hostname) + 1 }}"

- name: create configuration directory
  file:
    path: /etc/wireguard
    state: directory

- name: create configuration
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  notify: restart wg-quick@wg0

- meta: flush_handlers

- name: start wireguard
  systemd:
    name: "wg-quick@wg0"
    enabled: yes
    state: started
