---
- name: Install wireguard ppa
  apt_repository:
    filename: unstable-wireguard
    repo: 'ppa:wireguard/wireguard'
    update_cache: yes

- name: Configure wireguard repo (Debian)
  blockinfile:
    path: /etc/apt/preferences.d/limit-unstable
    create: yes
    block: |-
      Package: *
      Pin: release a=unstable
      Pin-Priority: 150

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - linux-headers-{{ ansible_kernel }}
    - software-properties-common

- name: Enable net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: yes
    state: present

  - name: Install wireguard
  apt:
    name: wireguard
    state: present

- name: Generate private keys
  shell: wg genkey
  register: wireguard_genkey
  changed_when: false

- set_fact:
    private_key: "{{ wireguard_genkey.stdout }}"

- name: Generate public keys
  shell: "echo {{ private_key }} | wg pubkey"
  register: wireguard_pubkey
  changed_when: false

- set_fact:
    public_key: "{{ wireguard_pubkey.stdout }}"

- set_fact: private_ip="10.0.1.{{ groups['wireguard'].index(inventory_hostname) + 1 }}"

- name: Create wireguard directory
  file:
    path: /etc/wireguard
    state: directory

- name: Configuring wireguard
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 600

- name: Starting wireguard
  systemd:
    name: "wg-quick@wg0"
    enabled: yes
    state: started