---
- name: add ppa
  apt_repository:
    filename: wireguard
    repo: 'ppa:wireguard/wireguard'
    update_cache: yes

- name: install package
  apt:
    name: wireguard
    state: present
# ensure fixed version

# do not recreate key with every ansible play
- name: Generate private keys
  shell: wg genkey
  register: wireguard_genkey
  changed_when: false

- name: remember wireguard_private_key
  set_fact:
    wireguard_private_key: "{{ wireguard_genkey.stdout }}"

- name: Generate public keys
  shell: "echo {{ wireguard_private_key }} | wg pubkey"
  register: wireguard_pubkey
  changed_when: false

- name: remember wireguard_public_key
  set_fact:
    wireguard_public_key: "{{ wireguard_pubkey.stdout }}"

- name: remember wireguard_private_ip
  set_fact:
    wireguard_private_ip: "10.0.1.{{ groups['all'].index(inventory_hostname) + 1 }}"

- name: Create wireguard directory
  file:
    path: /etc/wireguard
    state: directory

- name: Configuring wireguard
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 600
# TODO notify wg0 restart

- name: starting wireguard
  systemd:
    name: "wg-quick@wg0"
    enabled: yes
    state: started